version: '3'

services:
  casepro-postgres:
    image: mislavcimpersak/postgres_hstore
    environment:
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
    expose:
      - "${POSTGRES_PORT}"
    restart: always
    command: -p "${POSTGRES_PORT}"
#    networks:
#      - casepro-backend

  casepro-redis:
    image: redis
    command: redis-server --requirepass ${REDIS_PASSWORD} --port ${REDIS_PORT}
    expose:
      - "${REDIS_PORT}"
    restart: always
    environment:
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
#    networks:
#      - casepro-backend

  casepro-http:
    build: .
    image: psychomantys/casepro
    ports:
     - "8000:8000"
     - "8001:8001"
    depends_on:
      - casepro-redis
      - casepro-postgres
    restart: always
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB_NAME: ${POSTGRES_DB_NAME}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      DJANGO_SUPERUSER_USER: ${DJANGO_SUPERUSER_USER}
      DJANGO_SUPERUSER_PASSWORD: ${DJANGO_SUPERUSER_PASSWORD}
      DJANGO_SUPERUSER_EMAIL: ${DJANGO_SUPERUSER_EMAIL}
#    networks:
#      - casepro-backend

  casepro-celery-celery:
    build: .
    image: psychomantys/casepro
    command: celery worker -A casepro -Q celery -B -n casepro.celery --loglevel=INFO
    restart: always
    depends_on:
      - casepro-redis
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB_NAME: ${POSTGRES_DB_NAME}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
#    networks:
#      - casepro-backend

  casepro-celery-sync:
    build: .
    image: psychomantys/casepro
    command: celery worker -A casepro -Q sync -n casepro.sync --loglevel=INFO
    restart: always
    depends_on:
      - casepro-redis
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB_NAME: ${POSTGRES_DB_NAME}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}

#    networks:
#      - casepro-backend

#networks:
#  casepro-backend:
#    driver: bridge

