apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f - -v -o kubernetes/
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: casepro-redis
  name: casepro-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: casepro-redis
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f - -v -o kubernetes/
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: casepro-redis
    spec:
      containers:
      - args:
        - redis-server
        - --requirepass
        - asdaSDeEEEK
        - --port
        - "6379"
        env:
        - name: REDIS_HOST
          value: casepro-redis
        - name: REDIS_PASSWORD
          value: asdaSDeEEEK
        - name: REDIS_PORT
          value: "6379"
        image: redis
        imagePullPolicy: ""
        name: casepro-redis
        ports:
        - containerPort: 6379
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
