apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f - -v -o kubernetes/
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: casepro-redis
  name: casepro-redis
spec:
  ports:
  - name: "6379"
    port: 6379
    targetPort: 6379
  selector:
    io.kompose.service: casepro-redis
status:
  loadBalancer: {}
