apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f - -v -o kubernetes/
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: casepro-http
  name: casepro-http
spec:
  ports:
  - name: "8000"
    port: 8000
    targetPort: 8000
  - name: "8001"
    port: 8001
    targetPort: 8001
  selector:
    io.kompose.service: casepro-http
status:
  loadBalancer: {}
