apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f - -v -o kubernetes/
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: casepro-http
  name: casepro-http
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: casepro-http
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f - -v -o kubernetes/
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: casepro-http
    spec:
      containers:
      - env:
        - name: DJANGO_SUPERUSER_EMAIL
          value: root@root.com
        - name: DJANGO_SUPERUSER_PASSWORD
          value: ia2j5dXYA1
        - name: DJANGO_SUPERUSER_USER
          value: root
        - name: POSTGRES_DB_NAME
          value: casepro
        - name: POSTGRES_HOST
          value: casepro-postgres
        - name: POSTGRES_PASSWORD
          value: nyaruka
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_USER
          value: casepro
        - name: REDIS_HOST
          value: casepro-redis
        - name: REDIS_PASSWORD
          value: asdaSDeEEEK
        - name: REDIS_PORT
          value: "6379"
        image: psychomantys/casepro
        imagePullPolicy: ""
        name: casepro-http
        ports:
        - containerPort: 8000
        - containerPort: 8001
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
